### ISSUE TITLE
Preview invoice layout issue

### ISSUE THREAD

**Issue by huyphams** [hql287/Manta#131]
**Is it a bug or a feature request?**

- [x] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [x] macOS
- [ ] Windows
- [ ] Linux

**Which is the version/distribution of the OS?**

- I'm always up to date (all software and OSX).

- I got stuck on this screen, it's too big.
<img width="1440" alt="screen shot 2018-01-05 at 3 28 17 pm" src="https://user-images.githubusercontent.com/3654622/34601160-4d9bb576-f22d-11e7-80bb-5f77d3322366.png">

**Steps to replicate**

1. Preview invoice

**Comment by hql287** [comment]
@huyphams It's a known issue #48 and has been fixed with #56. You can either pull the newest code and use the dev version or wait until I fix #124  and release v1.1 (expected release date is Jan 11, 2018). 

Btw, I like what you're doing with TablePlus 👍 Would love to contribute to the project somehow but I think it's not open source atm?

**Comment by huyphams** [comment]
Thanks but I didn't have any plan to open source at this time (but maybe will open source some of TablePlus's components in the future). I dev TablePlus in my free time and there are a lot of features ahead. 
TablePlus will have plugin soon  (in pure javascript), people can contribute to it, just like Sketch does.

**Comment by hql287** [comment]
@huyphams: Sounds great 👍 I would like to see some improvement in the current UI, too. If you need someone to contribute to the project, let me know :)
