### ISSUE TITLE
Failed to open indexedDB

### ISSUE THREAD

**Issue by Hedronmx** [hql287/Manta#136]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [X] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
- [ ] Windows
- [X] Linux

**Which is the version/distribution of the OS?**

Elementary Os Loki 0.4.1 based on Ubuntu

**Describe your issue**
After closing the app and reopening I get the following error in console
"Failed to open indexedDB, are you in private browsing mode?"

**Steps to replicate**
Close application after creating a user.
Open application, error comes as "Unknown" inside the main window and in console "Failed to open indexedDB, are you in private browsing mode?"

**Comment by c0b41** [comment]
can you share stack trace?

**Comment by hql287** [comment]
Are you running both the exported app and the development mode?

**Comment by Hedronmx** [comment]
@hql287 I'm running the deb file and git clone, ran with the command Yarn dev and Yarn start. Both have the problem.

**Comment by Hedronmx** [comment]
/home/carlos/Documents/manta/node_modules/pouchdb-browser/lib/index.js:591 Failed to open indexedDB, are you in private browsing mode?
guardedConsole @ /home/carlos/Documents/manta/node_modules/pouchdb-browser/lib/index.js:591
req.onerror @ /home/carlos/Documents/manta/node_modules/pouchdb-browser/lib/index.js:6470

**Comment by Hedronmx** [comment]
It seems that Manta never closes. I checked on 3 computers and in all of them Manta services keep running. 2 Windows pc, 1 Linux. Manta keeps showing in the activity monitor / task manager. If I kill the process, the app can access the database.

**Comment by hql287** [comment]
@Hedronmx Yes, it's intentional that the app will remain running when you close its windows. To really quit the app, you can use the shortcut or use quit from the app's menu. 

I think you run into this problem is because the exported app was still running and you opened the dev server so there's a potential conflict. 

Anyway, if you quit both and try again, does the problem still persist?

**Comment by Hedronmx** [comment]
The thing is, in windows and Linux there's not quit app menu button. So I don't know how to correctly quit, unless I add a menu button in code. Also the app should only stay open in OSX after pressing the x button in the window, unless you add a tray icon in windows and linux.

**Comment by hql287** [comment]
I think you're right, this behaviour is not common in Windows/Linux and I should have made it the way Windows/Linux users would expect. 

Anyway, just want to confirm, if you run only the exported app or the dev server, the error won't occur, correct? If so, I will create another issue for the confusing behaviour of Manta on Linux/Windows rather than the error described here.

**Comment by Hedronmx** [comment]
Yes! The problem is that when you close the main window and you open another instance of the program, the newest instance can't access the database. Regarless if its the dev server o the exported app. Only by closing the processes can you access the database again.

And yes, create another issue stating the way manta handles closing in Windows and Linux. In the meantime I will try and do a quick hotfix for closing the app in windows and linux. I'll let you know what I come up with. Thanks!

**Comment by hql287** [comment]
> And yes, create another issue stating the way manta handles closing in Windows and Linux

Will do!

> In the meantime I will try and do a quick hotfix for closing the app in windows and linux.

Would love to see this as a PR, haha 😜

**Comment by Hedronmx** [comment]
Surething! >:D

**Comment by hql287** [comment]
Alright, closing this in favor of https://github.com/hql287/Manta/issues/141
