### ISSUE TITLE
Convert JSX to JS

### ISSUE THREAD

**Issue by deadcoder0904** [hql287/Manta#204]
I don't think there is any reason to use JSX now. 

Because the beginners starting React now won't know that the extension JSX works too.

**Comment by hql287** [comment]
> Because the beginners starting React now won't know that the extension JSX works too.

I think I can understand what you meant. I hated JSX when I first looked at it, too but now I can't imagine how I would live without it. Plus, I don't think this is a good justification for not using JSX. 

> I don't think there is any reason to use JSX now.

I'm open for changes but I do need more compelling reasons (than just a subjective statement) to do so. Since JSX is still being used in React doc I don't think it's gonna go away anytime soon.

**Comment by deadcoder0904** [comment]
Hey I was just stating about the extension man. `.jsx` to `.js` as it is a standard. But its not that important either.
